# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Io.js and Node.js.
environment:
  nodejs_version: "11"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install -g node-gyp
  - npm install -g electron-packager
  - npm install
  - npm audit fix
  - cmd: electron-packager . sonar --overwrite --asar --platform=win32 --arch=ia32 --icon=asset/logo.ico --prune=true --out=release-builds --version-string.CompanyName=\"minerstat OÜ\" --version-string.FileDescription=\"sonar\" --version-string.ProductName=\"sonar\"
  - cmd: rm package.json
  - cmd: rename package-armv7l.json package.json
  - cmd: npm install
  - cmd: npm audit fix
  - cmd: electron-packager . sonar --overwrite --asar --platform=linux --arch=x64 --icon=asset/1024x1024.png --prune=true --out=release-builds
  - cmd: electron-packager . sonar --overwrite --asar --platform=linux --arch=armv7l --icon=asset/1024x1024.png --prune=true --out=release-builds

artifacts:
- path: release-builds/sonar-win32-ia32
  name: minerstat-sonar-windows
- path: release-builds/sonar-linux-x64
  name: minerstat-sonar-linux
- path: release-builds/sonar-linux-armv7l
  name: minerstat-sonar-raspberry

deploy:
- provider: GitHub
  tag: latest
  release: continuous build - up to date with commits
  auth_token:
    secure: 8+BupHQlNXPEwEnEiWuiYCZhaqrRmxys2RnfVbMjttXFMeMIFkzKJPRbDMJlE+Jy
  repository: minerstat/minerstat-sonar
  prerelease: true
  force_update: true

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

# Don't actually build.
build: off
